services:
  front:
    image: nginx:stable-alpine
    container_name: softpoint
    volumes:
      - ./:/usr/src/app:ro
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 3000:3000
    restart: no
